# -*- coding: utf-8 -*-
"""Lavisha_Workshop 3_Assignment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPbl2bJvpQqvXaNmn8QWElKDdj0cNLTV
"""

# importing the necessary libraries
import pandas as pd
import re

# reading the dataset and observing the patterns
df = pd.read_csv("twitter_analysis.csv", encoding='latin-1')
df.head()

df.columns = ['target', 'id', 'date', 'flag', 'user', 'text'] # giving the names to columns of dataset for better understanding

df.shape # checking how large is the dataset

"""Now some commands below are just to analyze some basic patterns in the dataset which includes checking for missing and duplicate values."""

df.info()

df['target'].value_counts()

df['text_length'] = df['text'].apply(len)
df['text_length'].describe()

from collections import Counter

all_words = " ".join(df['text']).lower().split()
Counter(all_words).most_common(10)

df.isnull().sum()

df.duplicated().sum()

# check for noisy patterns in the dataset
df['has_url'] = df['text'].apply(lambda x: bool(re.search(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', x)))
df['has_html'] = df['text'].apply(lambda x: bool(re.search(r'<[^>]*>', x)))
df['has_mention'] = df['text'].apply(lambda x: bool(re.search(r'@\w+', x)))
df['has_hashtag'] = df['text'].apply(lambda x: bool(re.search(r'#\w+', x)))
df['has_extra_spaces'] = df['text'].apply(lambda x: bool(re.search(r'\s{2,}', x)))
df['has_special_chars'] = df['text'].apply(lambda x: bool(re.search(r'[^a-zA-Z0-9\s]', x)))

print("URLs:", df['has_url'].sum())
print("HTML tags:", df['has_html'].sum())
print("Mentions:", df['has_mention'].sum())
print("Hashtags:", df['has_hashtag'].sum())
print("Extra spaces:", df['has_extra_spaces'].sum())
print("Special characters:", df['has_special_chars'].sum())

# Cleaning the dataset using RegEx based text preprocessing technique
def clean_text(text):
    # convert to lowercase
    text = text.lower()

    # remove urls
    text = re.sub(r'(http\S+|www\S+|\S+\.\S+)', '', text)

    # remove html tags
    text = re.sub(r'<[^>]*>', '', text)

    # remove mentions (@user)
    text = re.sub(r'@\w+', '', text)

    # remove only '#' symbol but keep the word
    text = re.sub(r'#', '', text)

    # remove special characters / punctuation
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # remove extra spaces
    text = re.sub(r'\s{2,}', ' ', text).strip()

    return text

# apply cleaning
df['clean_text'] = df['text'].apply(clean_text)

#  Validate cleaning by recchhecking patterns

df['clean_has_url'] = df['clean_text'].apply(
    lambda x: bool(re.search(r'http\S+|www\S+', x))
)

df['clean_has_html'] = df['clean_text'].apply(
    lambda x: bool(re.search(r'<[^>]*>', x))
)

df['clean_has_mention'] = df['clean_text'].apply(
    lambda x: bool(re.search(r'@\w+', x))
)

df['clean_has_hashtag'] = df['clean_text'].apply(
    lambda x: bool(re.search(r'#\w+', x))
)

df['clean_has_extra_spaces'] = df['clean_text'].apply(
    lambda x: bool(re.search(r'\s{2,}', x))
)

df['clean_has_special_chars'] = df['clean_text'].apply(
    lambda x: bool(re.search(r'[^a-zA-Z0-9\s]', x))
)

# verifying that the dataset is properly cleaned.
#Note that there still exists 3 URLS after cleaning due to uncommon or irregular URL formats which is common in real world.
print("After Cleaning:")
print("URLs:", df['clean_has_url'].sum())
print("HTML tags:", df['clean_has_html'].sum())
print("Mentions:", df['clean_has_mention'].sum())
print("Hashtags:", df['clean_has_hashtag'].sum())
print("Extra spaces:", df['clean_has_extra_spaces'].sum())
print("Special characters:", df['clean_has_special_chars'].sum())

for i in range(10): #for compraison
    print("Original :", df['text'].iloc[i])
    print("Cleaned  :", df['clean_text'].iloc[i])
    print()

final_df = df[['target', 'id', 'date', 'flag', 'user', 'text', 'clean_text']].copy()

final_df.to_csv("clean_twitter_analysis.csv", index=False) #saving the clean output in a csv file